"""Generate source/levels.h from levels/*.txt in levels/order.txt order.

Run from the speck/ folder: python tools/gen_levels.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from levels_io import GH, load_levels  # noqa: E402

tagged = load_levels(with_tags=True)
levels = [(n, r) for n, r, _ in tagged]
tags = [t for _, _, t in tagged]
out = [
    "// Generated by tools/gen_levels.py from levels/ - edit the .txt files, not this.",
    "#pragma once",
    "",
    f"#define NLEVELS {len(levels)}",
    "static const char *const levels[NLEVELS][GH] = {",
]
for name, rows in levels:
    if len(rows) != GH:
        sys.exit(f"gen_levels: {name}.txt has {len(rows)} rows, want {GH}")
    out.append(f"    {{ // {name}")
    out += [f'        "{r}",' for r in rows]
    out.append("    },")
out.append("};")
# Display names for the level banner: "hopper" -> "the hopper", "two-thwomps" -> "two thwomps".
out.append("static const char *const level_names[NLEVELS] = {")
for name, _ in levels:
    label = name.replace("-", " ")
    if not label.startswith(("the ", "two ")):
        label = "the " + label
    out.append(f'    "{label}",')
out.append("};")
# Levels tagged no-sand in order.txt: stamping is off (pure platforming).
out.append("static const u8 level_no_sand[NLEVELS] = {")
out.append("    " + ", ".join("1" if "no-sand" in t else "0" for t in tags) + ",")
out.append("};")
new = "\n".join(out) + "\n"

path = os.path.join("source", "levels.h")
old = open(path, encoding="utf-8").read() if os.path.exists(path) else ""
if new != old:  # keep the timestamp when nothing changed
    open(path, "w", encoding="utf-8", newline="\n").write(new)
print(f"levels.h: {len(levels)} levels")
